#!/bin/env bash

export descanso="/opt/descanso"
export guiconfigproj="/Zanthus/Zeus/pdvJava/pdvGUI/guiConfigProj"
export pdvshelld="/usr/share/pdv-shell"
#export pdvrooton=""$pdvshelld"/pdv_root-on.sh"
export pdvcripto="$pdvshelld/pdv_cripto.sh"
export pdvrooton="$pdvshelld/pdv_root-on-ssh.sh"
export ipdv="$HOME/ip.txt"
export iponpdv="$HOME/ip_on.txt"
export ipoffpdv="$HOME/ip_off.txt"
export iponupgradepdv="$HOME/ip_on_upgrade.txt"
export pdvcripto="$pdvshelld/pdv_cripto.sh"
export sshpass_file=~/.ssh/pdvssl
export encryption_key_file=~/.ssh/pdv-encryption_key
#export rsync_options="-avz --no-checksum --no-owner --no-group -e"
#export rsync_options="-ahvz --no-checksum --no-owner --no-group -e"
#export rsync_options="-avz --delete --no-checksum --no-owner --no-group -e"
export rsync_options="-ahvz --delete --no-checksum --no-owner --no-group -e"
#export rsync_options="-az --info=progress2 --no-checksum --no-owner --no-group -e"
#export rsync_options="-ahz --info=progress2 --no-checksum --no-owner --no-group -e"
#export rsync_options="-az --delete --info=progress2 --no-checksum --no-owner --no-group -e"
#export rsync_options="-ahz --delete --info=progress2 --no-checksum --no-owner --no-group -e"

